let name = prompt("이름");
let type = prompt("운동종류");
let time = prompt("칼로리");
console.log("[운동 기록]");
console.log("이름");
console.log(name);
console.log("운동종류");
console.log(type);
console.log("운동시간"); 
console.log(time);
칼로리 = time * 7;
console.log("칼로리");
console.log(칼로리);